### ISSUE TITLE
Einarbeitung

### ISSUE THREAD

**Issue by steinroe** [pulseshift/lunch-pwa#1]
In der README findet ihr Links für einen guten Start.

**Comment by GeJulia** [comment]
14.03.2018 Einarbeitung , Installation aller Packages, Erstellung eines eigenen kleinen Projekts (ist leider nicht allzu kreativ geworden)
120min

**Comment by xyqa** [comment]
@JanScheuermann bist du fertig? der issue war due am 21.03
